{
 "title": "Museclient Dashboard",
 "description": "Dashboard for Museclient Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Museclient Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pending Transaction Goerli Localnet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "museclient_pending_txs_goerli_localnet",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hotkey Burn Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "museclient_hotkey_burn_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pending Transactions BTC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "museclient_pending_txs_btc_regtest",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Transaction Sign Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "museclient_Outbound_tx_sign_count{instance=\"172.20.0.21:8886\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BlockByNo Count Goerli/Localnet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "museclient_rpc_getBlockByNumber_count_goerli_localnet",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}