// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: musechain/musecore/crosschain/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the crosschain module's genesis state.
type GenesisState struct {
	OutboundTrackerList   []OutboundTracker   `protobuf:"bytes,2,rep,name=outboundTrackerList,proto3" json:"outboundTrackerList"`
	GasPriceList          []*GasPrice         `protobuf:"bytes,5,rep,name=gasPriceList,proto3" json:"gasPriceList,omitempty"`
	CrossChainTxs         []*CrossChainTx     `protobuf:"bytes,7,rep,name=CrossChainTxs,proto3" json:"CrossChainTxs,omitempty"`
	LastBlockHeightList   []*LastBlockHeight  `protobuf:"bytes,8,rep,name=lastBlockHeightList,proto3" json:"lastBlockHeightList,omitempty"`
	InboundHashToCctxList []InboundHashToCctx `protobuf:"bytes,9,rep,name=inboundHashToCctxList,proto3" json:"inboundHashToCctxList"`
	InboundTrackerList    []InboundTracker    `protobuf:"bytes,11,rep,name=inbound_tracker_list,json=inboundTrackerList,proto3" json:"inbound_tracker_list"`
	MuseAccounting        MuseAccounting      `protobuf:"bytes,12,opt,name=muse_accounting,json=museAccounting,proto3" json:"muse_accounting"`
	FinalizedInbounds     []string            `protobuf:"bytes,16,rep,name=FinalizedInbounds,proto3" json:"FinalizedInbounds,omitempty"`
	RateLimiterFlags      RateLimiterFlags    `protobuf:"bytes,17,opt,name=rate_limiter_flags,json=rateLimiterFlags,proto3" json:"rate_limiter_flags"`
	Counter               uint64              `protobuf:"varint,18,opt,name=counter,proto3" json:"counter,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e56b7a05f9256d0f, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetOutboundTrackerList() []OutboundTracker {
	if m != nil {
		return m.OutboundTrackerList
	}
	return nil
}

func (m *GenesisState) GetGasPriceList() []*GasPrice {
	if m != nil {
		return m.GasPriceList
	}
	return nil
}

func (m *GenesisState) GetCrossChainTxs() []*CrossChainTx {
	if m != nil {
		return m.CrossChainTxs
	}
	return nil
}

func (m *GenesisState) GetLastBlockHeightList() []*LastBlockHeight {
	if m != nil {
		return m.LastBlockHeightList
	}
	return nil
}

func (m *GenesisState) GetInboundHashToCctxList() []InboundHashToCctx {
	if m != nil {
		return m.InboundHashToCctxList
	}
	return nil
}

func (m *GenesisState) GetInboundTrackerList() []InboundTracker {
	if m != nil {
		return m.InboundTrackerList
	}
	return nil
}

func (m *GenesisState) GetMuseAccounting() MuseAccounting {
	if m != nil {
		return m.MuseAccounting
	}
	return MuseAccounting{}
}

func (m *GenesisState) GetFinalizedInbounds() []string {
	if m != nil {
		return m.FinalizedInbounds
	}
	return nil
}

func (m *GenesisState) GetRateLimiterFlags() RateLimiterFlags {
	if m != nil {
		return m.RateLimiterFlags
	}
	return RateLimiterFlags{}
}

func (m *GenesisState) GetCounter() uint64 {
	if m != nil {
		return m.Counter
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "musechain.musecore.crosschain.GenesisState")
}

func init() {
	proto.RegisterFile("musechain/musecore/crosschain/genesis.proto", fileDescriptor_e56b7a05f9256d0f)
}

var fileDescriptor_e56b7a05f9256d0f = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x1b, 0x36, 0x36, 0xe6, 0x0d, 0xd8, 0xbc, 0x21, 0x45, 0x95, 0x08, 0x15, 0x17, 0x2a,
	0x6d, 0x4d, 0xd0, 0x06, 0x88, 0xeb, 0x5a, 0xa9, 0x1b, 0xa2, 0x08, 0x08, 0x95, 0x90, 0x10, 0x92,
	0x71, 0x3c, 0x2f, 0xb1, 0x96, 0xc6, 0x95, 0xed, 0x48, 0x85, 0x4f, 0xc1, 0xc7, 0xda, 0x71, 0xc7,
	0x9d, 0x10, 0x6a, 0xbf, 0x08, 0x8a, 0xe3, 0x96, 0xa5, 0xad, 0x92, 0xde, 0x5e, 0xdd, 0xf7, 0x7b,
	0xbf, 0xa7, 0xfc, 0x6d, 0x70, 0x38, 0x48, 0x25, 0x25, 0x11, 0x66, 0x89, 0xa7, 0x2b, 0x2e, 0xa8,
	0x47, 0x04, 0x97, 0x32, 0x3f, 0x0b, 0x69, 0x42, 0x25, 0x93, 0xee, 0x50, 0x70, 0xc5, 0xe1, 0xd3,
	0x59, 0xb3, 0x3b, 0x6d, 0x76, 0xff, 0x37, 0xd7, 0x8f, 0xcb, 0x67, 0xe9, 0x12, 0xe9, 0x1a, 0xa9,
	0x51, 0x3e, 0xb2, 0xde, 0xaa, 0xf0, 0x63, 0x89, 0x86, 0x82, 0x11, 0x6a, 0xda, 0xdf, 0x96, 0xb7,
	0xb3, 0x24, 0xe0, 0x69, 0x72, 0x81, 0x22, 0x2c, 0x23, 0xa4, 0x38, 0x22, 0x64, 0x26, 0x3a, 0x59,
	0x8d, 0x54, 0x02, 0x93, 0x2b, 0x2a, 0x0c, 0xf4, 0xba, 0x1c, 0x8a, 0xb1, 0x54, 0x28, 0x88, 0x39,
	0xb9, 0x42, 0x11, 0x65, 0x61, 0xa4, 0x0c, 0xf6, 0xaa, 0x1c, 0xe3, 0xa9, 0x5a, 0x26, 0x7b, 0x53,
	0x4e, 0x09, 0xac, 0x28, 0x8a, 0xd9, 0x80, 0x29, 0x2a, 0xd0, 0x65, 0x8c, 0x43, 0x93, 0x4a, 0xfd,
	0x20, 0xe4, 0x21, 0xd7, 0xa5, 0x97, 0x55, 0xf9, 0xe9, 0xf3, 0xdb, 0x0d, 0xb0, 0x73, 0x96, 0xa7,
	0xf7, 0x45, 0x61, 0x45, 0xe1, 0x25, 0xd8, 0x9f, 0x8a, 0xfb, 0xb9, 0xb7, 0xc7, 0xa4, 0xb2, 0xef,
	0x35, 0xd6, 0x9a, 0xdb, 0xc7, 0xae, 0x5b, 0x1a, 0xad, 0xfb, 0xb1, 0x48, 0xb6, 0xd7, 0xaf, 0xff,
	0x3c, 0xab, 0xf9, 0xcb, 0x06, 0xc2, 0xf7, 0x60, 0x27, 0xc4, 0xf2, 0x53, 0x16, 0x9a, 0x16, 0xdc,
	0xd7, 0x82, 0x17, 0x15, 0x82, 0x33, 0x83, 0xf8, 0x05, 0x18, 0x7e, 0x06, 0x0f, 0x3b, 0x59, 0x53,
	0x27, 0x6b, 0xea, 0x8f, 0xa4, 0xbd, 0xa9, 0xa7, 0x1d, 0x56, 0x4c, 0xbb, 0xcb, 0xf8, 0xc5, 0x09,
	0xf0, 0x07, 0xd8, 0xcf, 0x72, 0x6b, 0x67, 0xb1, 0x9d, 0xeb, 0xd4, 0xf4, 0x9a, 0x0f, 0x56, 0xfa,
	0x0e, 0xbd, 0x22, 0xe9, 0x2f, 0x1b, 0x05, 0x63, 0xf0, 0xc4, 0x5c, 0xa7, 0x73, 0x2c, 0xa3, 0x3e,
	0xef, 0x10, 0x35, 0xd2, 0x8e, 0x2d, 0xed, 0x78, 0x59, 0xe1, 0x78, 0x37, 0xcf, 0x9a, 0xaf, 0xbd,
	0x7c, 0x28, 0xa4, 0xe0, 0x60, 0xee, 0xf2, 0xa2, 0x38, 0x93, 0x6d, 0x6b, 0x59, 0x6b, 0x35, 0x59,
	0x31, 0x57, 0xc8, 0x92, 0x85, 0x58, 0xbf, 0x83, 0xc7, 0x19, 0x8f, 0x30, 0x21, 0x3c, 0x4d, 0x14,
	0x4b, 0x42, 0x7b, 0xa7, 0x61, 0xad, 0x60, 0xf8, 0x90, 0x4a, 0x7a, 0x3a, 0x83, 0x8c, 0xe1, 0xd1,
	0xa0, 0x70, 0x0a, 0x8f, 0xc0, 0x5e, 0x97, 0x25, 0x38, 0x66, 0xbf, 0xe8, 0x85, 0x59, 0x49, 0xda,
	0xbb, 0x8d, 0xb5, 0xe6, 0x96, 0xbf, 0xf8, 0x07, 0x24, 0x00, 0x2e, 0xbe, 0x06, 0x7b, 0x4f, 0xaf,
	0xe3, 0x55, 0xac, 0xe3, 0x63, 0x45, 0x7b, 0x39, 0xd7, 0xcd, 0x30, 0xb3, 0xd0, 0xae, 0x98, 0x3b,
	0x87, 0x36, 0xd8, 0xd4, 0xeb, 0x51, 0x61, 0xc3, 0x86, 0xd5, 0x5c, 0xf7, 0xa7, 0x3f, 0xdb, 0xdd,
	0xeb, 0xb1, 0x63, 0xdd, 0x8c, 0x1d, 0xeb, 0xef, 0xd8, 0xb1, 0x7e, 0x4f, 0x9c, 0xda, 0xcd, 0xc4,
	0xa9, 0xdd, 0x4e, 0x9c, 0xda, 0xb7, 0xa3, 0x90, 0xa9, 0x28, 0x0d, 0x5c, 0xc2, 0x07, 0x9e, 0xff,
	0xf5, 0x54, 0xb6, 0x62, 0x1c, 0x48, 0xfd, 0x9a, 0xbd, 0xd1, 0xdd, 0xb7, 0xac, 0x7e, 0x0e, 0xa9,
	0x0c, 0x36, 0xf4, 0x4b, 0x3d, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x89, 0xf1, 0x74, 0x39, 0x84,
	0x05, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Counter != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Counter))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	{
		size, err := m.RateLimiterFlags.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x8a
	if len(m.FinalizedInbounds) > 0 {
		for iNdEx := len(m.FinalizedInbounds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FinalizedInbounds[iNdEx])
			copy(dAtA[i:], m.FinalizedInbounds[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.FinalizedInbounds[iNdEx])))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	}
	{
		size, err := m.MuseAccounting.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if len(m.InboundTrackerList) > 0 {
		for iNdEx := len(m.InboundTrackerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InboundTrackerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.InboundHashToCctxList) > 0 {
		for iNdEx := len(m.InboundHashToCctxList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InboundHashToCctxList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.LastBlockHeightList) > 0 {
		for iNdEx := len(m.LastBlockHeightList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LastBlockHeightList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.CrossChainTxs) > 0 {
		for iNdEx := len(m.CrossChainTxs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CrossChainTxs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.GasPriceList) > 0 {
		for iNdEx := len(m.GasPriceList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GasPriceList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.OutboundTrackerList) > 0 {
		for iNdEx := len(m.OutboundTrackerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OutboundTrackerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.OutboundTrackerList) > 0 {
		for _, e := range m.OutboundTrackerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GasPriceList) > 0 {
		for _, e := range m.GasPriceList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CrossChainTxs) > 0 {
		for _, e := range m.CrossChainTxs {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.LastBlockHeightList) > 0 {
		for _, e := range m.LastBlockHeightList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.InboundHashToCctxList) > 0 {
		for _, e := range m.InboundHashToCctxList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.InboundTrackerList) > 0 {
		for _, e := range m.InboundTrackerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.MuseAccounting.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.FinalizedInbounds) > 0 {
		for _, s := range m.FinalizedInbounds {
			l = len(s)
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	l = m.RateLimiterFlags.Size()
	n += 2 + l + sovGenesis(uint64(l))
	if m.Counter != 0 {
		n += 2 + sovGenesis(uint64(m.Counter))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundTrackerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutboundTrackerList = append(m.OutboundTrackerList, OutboundTracker{})
			if err := m.OutboundTrackerList[len(m.OutboundTrackerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasPriceList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GasPriceList = append(m.GasPriceList, &GasPrice{})
			if err := m.GasPriceList[len(m.GasPriceList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CrossChainTxs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CrossChainTxs = append(m.CrossChainTxs, &CrossChainTx{})
			if err := m.CrossChainTxs[len(m.CrossChainTxs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastBlockHeightList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastBlockHeightList = append(m.LastBlockHeightList, &LastBlockHeight{})
			if err := m.LastBlockHeightList[len(m.LastBlockHeightList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InboundHashToCctxList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InboundHashToCctxList = append(m.InboundHashToCctxList, InboundHashToCctx{})
			if err := m.InboundHashToCctxList[len(m.InboundHashToCctxList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InboundTrackerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InboundTrackerList = append(m.InboundTrackerList, InboundTracker{})
			if err := m.InboundTrackerList[len(m.InboundTrackerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MuseAccounting", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MuseAccounting.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedInbounds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalizedInbounds = append(m.FinalizedInbounds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateLimiterFlags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RateLimiterFlags.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counter", wireType)
			}
			m.Counter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Counter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
