// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: musechain/musecore/crosschain/legacy_msgs.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	chains "github.com/RWAs-labs/muse/pkg/chains"
	coin "github.com/RWAs-labs/muse/pkg/coin"
	proofs "github.com/RWAs-labs/muse/pkg/proofs"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// legacy MsgAddOutboundTracker
// defined to keep codec compatibility
type MsgAddToOutTxTracker struct {
	Creator   string        `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ChainId   int64         `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Nonce     uint64        `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TxHash    string        `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Proof     *proofs.Proof `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	BlockHash string        `protobuf:"bytes,6,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	TxIndex   int64         `protobuf:"varint,7,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
}

func (m *MsgAddToOutTxTracker) Reset()         { *m = MsgAddToOutTxTracker{} }
func (m *MsgAddToOutTxTracker) String() string { return proto.CompactTextString(m) }
func (*MsgAddToOutTxTracker) ProtoMessage()    {}
func (*MsgAddToOutTxTracker) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e17fd215dfc980e, []int{0}
}
func (m *MsgAddToOutTxTracker) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddToOutTxTracker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddToOutTxTracker.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddToOutTxTracker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddToOutTxTracker.Merge(m, src)
}
func (m *MsgAddToOutTxTracker) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddToOutTxTracker) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddToOutTxTracker.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddToOutTxTracker proto.InternalMessageInfo

func (m *MsgAddToOutTxTracker) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAddToOutTxTracker) GetChainId() int64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *MsgAddToOutTxTracker) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *MsgAddToOutTxTracker) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *MsgAddToOutTxTracker) GetProof() *proofs.Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *MsgAddToOutTxTracker) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *MsgAddToOutTxTracker) GetTxIndex() int64 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

// legacy MsgAddInboundTracker
// defined to keep codec compatibility
type MsgAddToInTxTracker struct {
	Creator   string        `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ChainId   int64         `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TxHash    string        `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	CoinType  coin.CoinType `protobuf:"varint,4,opt,name=coin_type,json=coinType,proto3,enum=musechain.musecore.pkg.coin.CoinType" json:"coin_type,omitempty"`
	Proof     *proofs.Proof `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	BlockHash string        `protobuf:"bytes,6,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	TxIndex   int64         `protobuf:"varint,7,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
}

func (m *MsgAddToInTxTracker) Reset()         { *m = MsgAddToInTxTracker{} }
func (m *MsgAddToInTxTracker) String() string { return proto.CompactTextString(m) }
func (*MsgAddToInTxTracker) ProtoMessage()    {}
func (*MsgAddToInTxTracker) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e17fd215dfc980e, []int{1}
}
func (m *MsgAddToInTxTracker) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddToInTxTracker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddToInTxTracker.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddToInTxTracker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddToInTxTracker.Merge(m, src)
}
func (m *MsgAddToInTxTracker) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddToInTxTracker) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddToInTxTracker.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddToInTxTracker proto.InternalMessageInfo

func (m *MsgAddToInTxTracker) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAddToInTxTracker) GetChainId() int64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *MsgAddToInTxTracker) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *MsgAddToInTxTracker) GetCoinType() coin.CoinType {
	if m != nil {
		return m.CoinType
	}
	return coin.CoinType_Muse
}

func (m *MsgAddToInTxTracker) GetProof() *proofs.Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *MsgAddToInTxTracker) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *MsgAddToInTxTracker) GetTxIndex() int64 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

// legacy MsgRemoveOutboundTracker
// defined to keep codec compatibility
type MsgRemoveFromOutTxTracker struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ChainId int64  `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Nonce   uint64 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *MsgRemoveFromOutTxTracker) Reset()         { *m = MsgRemoveFromOutTxTracker{} }
func (m *MsgRemoveFromOutTxTracker) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveFromOutTxTracker) ProtoMessage()    {}
func (*MsgRemoveFromOutTxTracker) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e17fd215dfc980e, []int{2}
}
func (m *MsgRemoveFromOutTxTracker) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveFromOutTxTracker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveFromOutTxTracker.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveFromOutTxTracker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveFromOutTxTracker.Merge(m, src)
}
func (m *MsgRemoveFromOutTxTracker) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveFromOutTxTracker) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveFromOutTxTracker.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveFromOutTxTracker proto.InternalMessageInfo

func (m *MsgRemoveFromOutTxTracker) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRemoveFromOutTxTracker) GetChainId() int64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *MsgRemoveFromOutTxTracker) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

// legacy MsgVoteOutbound
// defined to keep codec compatibility
type MsgVoteOnObservedOutboundTx struct {
	Creator                        string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	CctxHash                       string                 `protobuf:"bytes,2,opt,name=cctx_hash,json=cctxHash,proto3" json:"cctx_hash,omitempty"`
	ObservedOutTxHash              string                 `protobuf:"bytes,3,opt,name=observed_outTx_hash,json=observedOutTxHash,proto3" json:"observed_outTx_hash,omitempty"`
	ObservedOutTxBlockHeight       uint64                 `protobuf:"varint,4,opt,name=observed_outTx_blockHeight,json=observedOutTxBlockHeight,proto3" json:"observed_outTx_blockHeight,omitempty"`
	ObservedOutTxGasUsed           uint64                 `protobuf:"varint,10,opt,name=observed_outTx_gas_used,json=observedOutTxGasUsed,proto3" json:"observed_outTx_gas_used,omitempty"`
	ObservedOutTxEffectiveGasPrice cosmossdk_io_math.Int  `protobuf:"bytes,11,opt,name=observed_outTx_effective_gas_price,json=observedOutTxEffectiveGasPrice,proto3,customtype=cosmossdk.io/math.Int" json:"observed_outTx_effective_gas_price"`
	ObservedOutTxEffectiveGasLimit uint64                 `protobuf:"varint,12,opt,name=observed_outTx_effective_gas_limit,json=observedOutTxEffectiveGasLimit,proto3" json:"observed_outTx_effective_gas_limit,omitempty"`
	ValueReceived                  cosmossdk_io_math.Uint `protobuf:"bytes,5,opt,name=value_received,json=valueReceived,proto3,customtype=cosmossdk.io/math.Uint" json:"value_received" yaml:"value_received"`
	Status                         chains.ReceiveStatus   `protobuf:"varint,6,opt,name=status,proto3,enum=musechain.musecore.pkg.chains.ReceiveStatus" json:"status,omitempty"`
	OutTxChain                     int64                  `protobuf:"varint,7,opt,name=outTx_chain,json=outTxChain,proto3" json:"outTx_chain,omitempty"`
	OutTxTssNonce                  uint64                 `protobuf:"varint,8,opt,name=outTx_tss_nonce,json=outTxTssNonce,proto3" json:"outTx_tss_nonce,omitempty"`
	CoinType                       coin.CoinType          `protobuf:"varint,9,opt,name=coin_type,json=coinType,proto3,enum=musechain.musecore.pkg.coin.CoinType" json:"coin_type,omitempty"`
}

func (m *MsgVoteOnObservedOutboundTx) Reset()         { *m = MsgVoteOnObservedOutboundTx{} }
func (m *MsgVoteOnObservedOutboundTx) String() string { return proto.CompactTextString(m) }
func (*MsgVoteOnObservedOutboundTx) ProtoMessage()    {}
func (*MsgVoteOnObservedOutboundTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e17fd215dfc980e, []int{3}
}
func (m *MsgVoteOnObservedOutboundTx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteOnObservedOutboundTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteOnObservedOutboundTx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteOnObservedOutboundTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteOnObservedOutboundTx.Merge(m, src)
}
func (m *MsgVoteOnObservedOutboundTx) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteOnObservedOutboundTx) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteOnObservedOutboundTx.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteOnObservedOutboundTx proto.InternalMessageInfo

func (m *MsgVoteOnObservedOutboundTx) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgVoteOnObservedOutboundTx) GetCctxHash() string {
	if m != nil {
		return m.CctxHash
	}
	return ""
}

func (m *MsgVoteOnObservedOutboundTx) GetObservedOutTxHash() string {
	if m != nil {
		return m.ObservedOutTxHash
	}
	return ""
}

func (m *MsgVoteOnObservedOutboundTx) GetObservedOutTxBlockHeight() uint64 {
	if m != nil {
		return m.ObservedOutTxBlockHeight
	}
	return 0
}

func (m *MsgVoteOnObservedOutboundTx) GetObservedOutTxGasUsed() uint64 {
	if m != nil {
		return m.ObservedOutTxGasUsed
	}
	return 0
}

func (m *MsgVoteOnObservedOutboundTx) GetObservedOutTxEffectiveGasLimit() uint64 {
	if m != nil {
		return m.ObservedOutTxEffectiveGasLimit
	}
	return 0
}

func (m *MsgVoteOnObservedOutboundTx) GetStatus() chains.ReceiveStatus {
	if m != nil {
		return m.Status
	}
	return chains.ReceiveStatus_created
}

func (m *MsgVoteOnObservedOutboundTx) GetOutTxChain() int64 {
	if m != nil {
		return m.OutTxChain
	}
	return 0
}

func (m *MsgVoteOnObservedOutboundTx) GetOutTxTssNonce() uint64 {
	if m != nil {
		return m.OutTxTssNonce
	}
	return 0
}

func (m *MsgVoteOnObservedOutboundTx) GetCoinType() coin.CoinType {
	if m != nil {
		return m.CoinType
	}
	return coin.CoinType_Muse
}

// legacy MsgVoteInbound
// defined to keep codec compatibility
type MsgVoteOnObservedInboundTx struct {
	Creator       string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Sender        string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderChainId int64  `protobuf:"varint,3,opt,name=sender_chain_id,json=senderChainId,proto3" json:"sender_chain_id,omitempty"`
	Receiver      string `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	ReceiverChain int64  `protobuf:"varint,5,opt,name=receiver_chain,json=receiverChain,proto3" json:"receiver_chain,omitempty"`
	//  string muse_burnt = 6;
	Amount cosmossdk_io_math.Uint `protobuf:"bytes,6,opt,name=amount,proto3,customtype=cosmossdk.io/math.Uint" json:"amount"`
	//  string mMint = 7;
	Message       string        `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	InTxHash      string        `protobuf:"bytes,9,opt,name=in_tx_hash,json=inTxHash,proto3" json:"in_tx_hash,omitempty"`
	InBlockHeight uint64        `protobuf:"varint,10,opt,name=in_block_height,json=inBlockHeight,proto3" json:"in_block_height,omitempty"`
	GasLimit      uint64        `protobuf:"varint,11,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	CoinType      coin.CoinType `protobuf:"varint,12,opt,name=coin_type,json=coinType,proto3,enum=musechain.musecore.pkg.coin.CoinType" json:"coin_type,omitempty"`
	TxOrigin      string        `protobuf:"bytes,13,opt,name=tx_origin,json=txOrigin,proto3" json:"tx_origin,omitempty"`
	Asset         string        `protobuf:"bytes,14,opt,name=asset,proto3" json:"asset,omitempty"`
	// event index of the sent asset in the observed tx
	EventIndex uint64 `protobuf:"varint,15,opt,name=event_index,json=eventIndex,proto3" json:"event_index,omitempty"`
}

func (m *MsgVoteOnObservedInboundTx) Reset()         { *m = MsgVoteOnObservedInboundTx{} }
func (m *MsgVoteOnObservedInboundTx) String() string { return proto.CompactTextString(m) }
func (*MsgVoteOnObservedInboundTx) ProtoMessage()    {}
func (*MsgVoteOnObservedInboundTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e17fd215dfc980e, []int{4}
}
func (m *MsgVoteOnObservedInboundTx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVoteOnObservedInboundTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVoteOnObservedInboundTx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVoteOnObservedInboundTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVoteOnObservedInboundTx.Merge(m, src)
}
func (m *MsgVoteOnObservedInboundTx) XXX_Size() int {
	return m.Size()
}
func (m *MsgVoteOnObservedInboundTx) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVoteOnObservedInboundTx.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVoteOnObservedInboundTx proto.InternalMessageInfo

func (m *MsgVoteOnObservedInboundTx) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgVoteOnObservedInboundTx) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgVoteOnObservedInboundTx) GetSenderChainId() int64 {
	if m != nil {
		return m.SenderChainId
	}
	return 0
}

func (m *MsgVoteOnObservedInboundTx) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *MsgVoteOnObservedInboundTx) GetReceiverChain() int64 {
	if m != nil {
		return m.ReceiverChain
	}
	return 0
}

func (m *MsgVoteOnObservedInboundTx) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MsgVoteOnObservedInboundTx) GetInTxHash() string {
	if m != nil {
		return m.InTxHash
	}
	return ""
}

func (m *MsgVoteOnObservedInboundTx) GetInBlockHeight() uint64 {
	if m != nil {
		return m.InBlockHeight
	}
	return 0
}

func (m *MsgVoteOnObservedInboundTx) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *MsgVoteOnObservedInboundTx) GetCoinType() coin.CoinType {
	if m != nil {
		return m.CoinType
	}
	return coin.CoinType_Muse
}

func (m *MsgVoteOnObservedInboundTx) GetTxOrigin() string {
	if m != nil {
		return m.TxOrigin
	}
	return ""
}

func (m *MsgVoteOnObservedInboundTx) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *MsgVoteOnObservedInboundTx) GetEventIndex() uint64 {
	if m != nil {
		return m.EventIndex
	}
	return 0
}

// legacy MsgVoteGasPrice
// defined to keep codec compatibility
type MsgGasPriceVoter struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ChainId     int64  `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Price       uint64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	BlockNumber uint64 `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Supply      string `protobuf:"bytes,5,opt,name=supply,proto3" json:"supply,omitempty"`
}

func (m *MsgGasPriceVoter) Reset()         { *m = MsgGasPriceVoter{} }
func (m *MsgGasPriceVoter) String() string { return proto.CompactTextString(m) }
func (*MsgGasPriceVoter) ProtoMessage()    {}
func (*MsgGasPriceVoter) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e17fd215dfc980e, []int{5}
}
func (m *MsgGasPriceVoter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgGasPriceVoter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgGasPriceVoter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgGasPriceVoter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgGasPriceVoter.Merge(m, src)
}
func (m *MsgGasPriceVoter) XXX_Size() int {
	return m.Size()
}
func (m *MsgGasPriceVoter) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgGasPriceVoter.DiscardUnknown(m)
}

var xxx_messageInfo_MsgGasPriceVoter proto.InternalMessageInfo

func (m *MsgGasPriceVoter) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgGasPriceVoter) GetChainId() int64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *MsgGasPriceVoter) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MsgGasPriceVoter) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *MsgGasPriceVoter) GetSupply() string {
	if m != nil {
		return m.Supply
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgAddToOutTxTracker)(nil), "musechain.musecore.crosschain.MsgAddToOutTxTracker")
	proto.RegisterType((*MsgAddToInTxTracker)(nil), "musechain.musecore.crosschain.MsgAddToInTxTracker")
	proto.RegisterType((*MsgRemoveFromOutTxTracker)(nil), "musechain.musecore.crosschain.MsgRemoveFromOutTxTracker")
	proto.RegisterType((*MsgVoteOnObservedOutboundTx)(nil), "musechain.musecore.crosschain.MsgVoteOnObservedOutboundTx")
	proto.RegisterType((*MsgVoteOnObservedInboundTx)(nil), "musechain.musecore.crosschain.MsgVoteOnObservedInboundTx")
	proto.RegisterType((*MsgGasPriceVoter)(nil), "musechain.musecore.crosschain.MsgGasPriceVoter")
}

func init() {
	proto.RegisterFile("musechain/musecore/crosschain/legacy_msgs.proto", fileDescriptor_6e17fd215dfc980e)
}

var fileDescriptor_6e17fd215dfc980e = []byte{
	// 1014 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0xaf, 0xb7, 0x6d, 0x1a, 0xbf, 0x34, 0x29, 0x78, 0xbb, 0x5b, 0x37, 0xa5, 0x69, 0x89, 0xd8,
	0xaa, 0x5a, 0x2d, 0x89, 0x28, 0x62, 0x91, 0x2a, 0x2e, 0x9b, 0xc2, 0x2e, 0x41, 0x74, 0xb3, 0x32,
	0x59, 0x90, 0x38, 0x60, 0x39, 0xf6, 0xd4, 0x19, 0x25, 0x9e, 0x89, 0x3c, 0xe3, 0xc8, 0xb9, 0xf2,
	0x09, 0x38, 0xf0, 0x19, 0xb8, 0x70, 0xe1, 0x63, 0xec, 0x71, 0x8f, 0x88, 0x43, 0x85, 0xda, 0x03,
	0x67, 0xf8, 0x00, 0x08, 0xf9, 0xcd, 0xb8, 0x6d, 0xb2, 0xfd, 0x23, 0x15, 0x21, 0x71, 0x89, 0xe7,
	0x3d, 0xbf, 0xdf, 0x9b, 0xf7, 0xe7, 0xf7, 0x5e, 0x0c, 0xcd, 0x28, 0x11, 0xc4, 0xef, 0x7b, 0x94,
	0xa9, 0x13, 0x8f, 0x49, 0xd3, 0x8f, 0xb9, 0x10, 0x4a, 0x37, 0x24, 0xa1, 0xe7, 0x4f, 0xdc, 0x48,
	0x84, 0xa2, 0x31, 0x8a, 0xb9, 0xe4, 0xd6, 0xe6, 0x19, 0xa0, 0x91, 0x03, 0x1a, 0xe7, 0x80, 0xea,
	0x9a, 0xcf, 0x45, 0xc4, 0x45, 0x33, 0x12, 0x61, 0x73, 0xfc, 0x41, 0xf6, 0x50, 0xb8, 0xea, 0x6a,
	0xc8, 0x43, 0x8e, 0xc7, 0x66, 0x76, 0xd2, 0xda, 0x87, 0x97, 0x5c, 0x3f, 0x1a, 0x84, 0x4d, 0x54,
	0x09, 0xfd, 0xd0, 0xb6, 0x3b, 0x57, 0xd9, 0x72, 0xca, 0xf0, 0xe7, 0x06, 0x9f, 0xa3, 0x98, 0xf3,
	0x23, 0xa1, 0x1f, 0xda, 0xf6, 0xf1, 0xf5, 0xe9, 0xc7, 0x9e, 0x24, 0xee, 0x90, 0x46, 0x54, 0x92,
	0xd8, 0x3d, 0x1a, 0x7a, 0x79, 0x15, 0xaa, 0x7b, 0xd7, 0xe3, 0xf0, 0xe8, 0xe2, 0xd9, 0x95, 0xa9,
	0xc2, 0xd4, 0xff, 0x36, 0x60, 0xf5, 0x50, 0x84, 0x4f, 0x82, 0xa0, 0xcb, 0x3b, 0x89, 0xec, 0xa6,
	0xdd, 0xd8, 0xf3, 0x07, 0x24, 0xb6, 0x6c, 0x58, 0xf2, 0x63, 0xe2, 0x49, 0x1e, 0xdb, 0xc6, 0xb6,
	0xb1, 0x6b, 0x3a, 0xb9, 0x68, 0xad, 0x43, 0x51, 0x39, 0xa1, 0x81, 0x7d, 0x67, 0xdb, 0xd8, 0x9d,
	0x77, 0x96, 0x50, 0x6e, 0x07, 0xd6, 0x2a, 0x2c, 0x32, 0xce, 0x7c, 0x62, 0xcf, 0x6f, 0x1b, 0xbb,
	0x0b, 0x8e, 0x12, 0xac, 0x35, 0x58, 0x92, 0xa9, 0xdb, 0xf7, 0x44, 0xdf, 0x5e, 0x40, 0x57, 0x05,
	0x99, 0x7e, 0xee, 0x89, 0xbe, 0xb5, 0x0f, 0x8b, 0x98, 0xb8, 0xbd, 0xb8, 0x6d, 0xec, 0x96, 0xf6,
	0xde, 0x6b, 0x5c, 0xd2, 0xc6, 0xd1, 0x00, 0x9b, 0x95, 0x55, 0xe7, 0x45, 0xf6, 0x70, 0x14, 0xc4,
	0xda, 0x04, 0xe8, 0x0d, 0xb9, 0x3f, 0x50, 0x7e, 0x0b, 0xe8, 0xd7, 0x44, 0x0d, 0xba, 0x5e, 0x87,
	0xa2, 0x4c, 0x5d, 0xca, 0x02, 0x92, 0xda, 0x4b, 0x2a, 0x48, 0x99, 0xb6, 0x33, 0x71, 0x7f, 0xf9,
	0xfb, 0x3f, 0x7e, 0x79, 0x98, 0x67, 0x53, 0xff, 0xf9, 0x0e, 0xdc, 0xcd, 0x0b, 0xd0, 0x66, 0xff,
	0x32, 0xff, 0x0b, 0x99, 0xce, 0x4f, 0x65, 0xda, 0x02, 0x33, 0x23, 0x83, 0x2b, 0x27, 0x23, 0x82,
	0x45, 0xa8, 0xec, 0x3d, 0xb8, 0x2a, 0x5b, 0x64, 0xcd, 0x01, 0xa7, 0xac, 0x3b, 0x19, 0x11, 0xa7,
	0xe8, 0xeb, 0xd3, 0xff, 0xa2, 0x5a, 0x12, 0xd6, 0x0f, 0x45, 0xe8, 0x90, 0x88, 0x8f, 0xc9, 0xd3,
	0x98, 0x47, 0xff, 0x11, 0x65, 0x66, 0x6e, 0xfd, 0x73, 0x11, 0x36, 0x0e, 0x45, 0xf8, 0x35, 0x97,
	0xa4, 0xc3, 0x3a, 0x3d, 0x41, 0xe2, 0x31, 0x09, 0x3a, 0x89, 0xec, 0xf1, 0x84, 0x05, 0xdd, 0xf4,
	0x9a, 0x8b, 0x37, 0xc0, 0xf4, 0xfd, 0xbc, 0x25, 0x77, 0xf0, 0x5d, 0x31, 0x53, 0x60, 0xd6, 0x0d,
	0xb8, 0xcb, 0xb5, 0x33, 0x97, 0x67, 0x89, 0x5c, 0xec, 0xdc, 0xdb, 0xfc, 0xfc, 0x9e, 0xae, 0xb2,
	0xff, 0x04, 0xaa, 0x33, 0xf6, 0xaa, 0x82, 0x84, 0x86, 0x7d, 0x89, 0x5d, 0x5d, 0x70, 0xec, 0x29,
	0x58, 0xeb, 0xfc, 0xbd, 0xf5, 0x11, 0xac, 0xcd, 0xa0, 0x43, 0x4f, 0xb8, 0x89, 0x20, 0x81, 0x0d,
	0x08, 0x5d, 0x9d, 0x82, 0x3e, 0xf3, 0xc4, 0x4b, 0x41, 0x02, 0x8b, 0x42, 0x7d, 0x06, 0x46, 0x8e,
	0x8e, 0x88, 0x2f, 0xe9, 0x98, 0xa0, 0x83, 0x51, 0x4c, 0x7d, 0x62, 0x97, 0xb2, 0x98, 0x5b, 0x9b,
	0xaf, 0x8e, 0xb7, 0xe6, 0x7e, 0x3b, 0xde, 0xba, 0xa7, 0xf6, 0x9d, 0x08, 0x06, 0x0d, 0xca, 0x9b,
	0x91, 0x27, 0xfb, 0x8d, 0x36, 0x93, 0x4e, 0x6d, 0xea, 0x82, 0xcf, 0x72, 0x37, 0xcf, 0x3c, 0xf1,
	0x22, 0x73, 0x62, 0x7d, 0x71, 0xc3, 0x55, 0xb8, 0x73, 0xec, 0x65, 0x0c, 0xf6, 0x6a, 0x5f, 0x5f,
	0x66, 0x56, 0xd6, 0x77, 0x50, 0x19, 0x7b, 0xc3, 0x84, 0xb8, 0x31, 0xf1, 0x09, 0x1d, 0x93, 0x00,
	0x59, 0x6b, 0xb6, 0x3e, 0xd6, 0x21, 0xde, 0x7f, 0x33, 0xc4, 0x97, 0x94, 0xc9, 0xbf, 0x8e, 0xb7,
	0xee, 0x4d, 0xbc, 0x68, 0xb8, 0x5f, 0x9f, 0x46, 0xd7, 0x9d, 0x32, 0x2a, 0x1c, 0x2d, 0x5b, 0x9f,
	0x42, 0x41, 0x48, 0x4f, 0x26, 0x02, 0xc9, 0x5c, 0xd9, 0x7b, 0x74, 0xe5, 0x34, 0xa9, 0x6d, 0xad,
	0x81, 0x5f, 0x21, 0xc6, 0xd1, 0x58, 0x6b, 0x0b, 0x4a, 0x2a, 0x51, 0xb4, 0xd2, 0xd4, 0x07, 0x54,
	0x1d, 0x64, 0x1a, 0x6b, 0x07, 0x56, 0x94, 0x81, 0x14, 0xc2, 0x55, 0x3c, 0x2d, 0x62, 0xfe, 0x65,
	0x54, 0x77, 0x85, 0x78, 0x8e, 0x2b, 0x6e, 0x6a, 0xbe, 0xcd, 0x5b, 0xcd, 0xf7, 0x0c, 0xe7, 0x7f,
	0x5c, 0x80, 0xea, 0x1b, 0x9c, 0x6f, 0xb3, 0x9b, 0x29, 0x7f, 0x1f, 0x0a, 0x82, 0xb0, 0x80, 0xc4,
	0x9a, 0xef, 0x5a, 0xca, 0x52, 0x51, 0x27, 0xf7, 0x6c, 0x14, 0xe7, 0x31, 0xdf, 0xb2, 0x52, 0x1f,
	0xe8, 0x81, 0xac, 0x42, 0x51, 0x57, 0x3d, 0xd6, 0xeb, 0xfa, 0x4c, 0xb6, 0x1e, 0x40, 0x25, 0x3f,
	0xeb, 0x92, 0x2d, 0x2a, 0x17, 0xb9, 0x56, 0x55, 0xed, 0x31, 0x14, 0xbc, 0x88, 0x27, 0x4c, 0xaa,
	0x4d, 0xd3, 0xaa, 0x5d, 0xdf, 0x74, 0x47, 0x5b, 0x67, 0x49, 0x45, 0x44, 0x08, 0x2f, 0x54, 0x55,
	0x36, 0x9d, 0x5c, 0xb4, 0xde, 0x01, 0xc0, 0x7f, 0x2d, 0x35, 0xa1, 0xa6, 0x0a, 0x8b, 0x32, 0x3d,
	0x98, 0x3b, 0xb0, 0x42, 0x99, 0xab, 0x17, 0x9c, 0x9a, 0x46, 0x35, 0x52, 0x65, 0xca, 0x2e, 0x8e,
	0xe0, 0x06, 0x98, 0xe7, 0x3c, 0x2e, 0xa1, 0x45, 0x31, 0xcc, 0x19, 0x3b, 0xd5, 0xc2, 0xe5, 0xdb,
	0xad, 0xe8, 0x0d, 0x30, 0x65, 0xea, 0xf2, 0x98, 0x86, 0x94, 0xd9, 0x65, 0x15, 0xa5, 0x4c, 0x3b,
	0x28, 0x67, 0x9b, 0xce, 0x13, 0x82, 0x48, 0xbb, 0x82, 0x2f, 0x94, 0x90, 0x51, 0x90, 0x8c, 0x09,
	0x93, 0x7a, 0xfb, 0xae, 0x60, 0x54, 0x80, 0xaa, 0xcb, 0x16, 0xf0, 0x4f, 0x06, 0xbc, 0x75, 0x28,
	0xc2, 0x7c, 0x66, 0x33, 0x7a, 0xdc, 0x7e, 0xf1, 0xaa, 0xdd, 0xa1, 0x17, 0x2f, 0x0a, 0xd6, 0xbb,
	0xb0, 0xac, 0xea, 0xc8, 0x92, 0xa8, 0xa7, 0x19, 0xb0, 0xe0, 0x94, 0x50, 0xf7, 0x1c, 0x55, 0x48,
	0xb0, 0x64, 0x34, 0x1a, 0x4e, 0xd4, 0x48, 0x3b, 0x5a, 0x9a, 0x0e, 0xb4, 0xf5, 0xf4, 0xd5, 0x49,
	0xcd, 0x78, 0x7d, 0x52, 0x33, 0x7e, 0x3f, 0xa9, 0x19, 0x3f, 0x9c, 0xd6, 0xe6, 0x5e, 0x9f, 0xd6,
	0xe6, 0x7e, 0x3d, 0xad, 0xcd, 0x7d, 0xfb, 0x28, 0xa4, 0xb2, 0x9f, 0xf4, 0x1a, 0x3e, 0x8f, 0x9a,
	0xce, 0x37, 0x4f, 0xc4, 0xfb, 0x43, 0xaf, 0x27, 0xf0, 0x8b, 0xa5, 0x99, 0x5e, 0xfc, 0x5e, 0xc9,
	0x1a, 0x21, 0x7a, 0x05, 0xfc, 0x4e, 0xf9, 0xf0, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0x5c,
	0xae, 0x0c, 0x14, 0x0a, 0x00, 0x00,
}

func (m *MsgAddToOutTxTracker) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddToOutTxTracker) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddToOutTxTracker) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TxIndex != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.TxIndex))
		i--
		dAtA[i] = 0x38
	}
	if len(m.BlockHash) > 0 {
		i -= len(m.BlockHash)
		copy(dAtA[i:], m.BlockHash)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.BlockHash)))
		i--
		dAtA[i] = 0x32
	}
	if m.Proof != nil {
		{
			size, err := m.Proof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLegacyMsgs(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x22
	}
	if m.Nonce != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x18
	}
	if m.ChainId != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.ChainId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddToInTxTracker) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddToInTxTracker) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddToInTxTracker) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TxIndex != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.TxIndex))
		i--
		dAtA[i] = 0x38
	}
	if len(m.BlockHash) > 0 {
		i -= len(m.BlockHash)
		copy(dAtA[i:], m.BlockHash)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.BlockHash)))
		i--
		dAtA[i] = 0x32
	}
	if m.Proof != nil {
		{
			size, err := m.Proof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLegacyMsgs(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.CoinType != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.CoinType))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ChainId != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.ChainId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveFromOutTxTracker) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveFromOutTxTracker) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveFromOutTxTracker) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Nonce != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x18
	}
	if m.ChainId != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.ChainId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgVoteOnObservedOutboundTx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteOnObservedOutboundTx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteOnObservedOutboundTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ObservedOutTxEffectiveGasLimit != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.ObservedOutTxEffectiveGasLimit))
		i--
		dAtA[i] = 0x60
	}
	{
		size := m.ObservedOutTxEffectiveGasPrice.Size()
		i -= size
		if _, err := m.ObservedOutTxEffectiveGasPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	if m.ObservedOutTxGasUsed != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.ObservedOutTxGasUsed))
		i--
		dAtA[i] = 0x50
	}
	if m.CoinType != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.CoinType))
		i--
		dAtA[i] = 0x48
	}
	if m.OutTxTssNonce != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.OutTxTssNonce))
		i--
		dAtA[i] = 0x40
	}
	if m.OutTxChain != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.OutTxChain))
		i--
		dAtA[i] = 0x38
	}
	if m.Status != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.ValueReceived.Size()
		i -= size
		if _, err := m.ValueReceived.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.ObservedOutTxBlockHeight != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.ObservedOutTxBlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ObservedOutTxHash) > 0 {
		i -= len(m.ObservedOutTxHash)
		copy(dAtA[i:], m.ObservedOutTxHash)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.ObservedOutTxHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CctxHash) > 0 {
		i -= len(m.CctxHash)
		copy(dAtA[i:], m.CctxHash)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.CctxHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgVoteOnObservedInboundTx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVoteOnObservedInboundTx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVoteOnObservedInboundTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EventIndex != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.EventIndex))
		i--
		dAtA[i] = 0x78
	}
	if len(m.Asset) > 0 {
		i -= len(m.Asset)
		copy(dAtA[i:], m.Asset)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.Asset)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.TxOrigin) > 0 {
		i -= len(m.TxOrigin)
		copy(dAtA[i:], m.TxOrigin)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.TxOrigin)))
		i--
		dAtA[i] = 0x6a
	}
	if m.CoinType != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.CoinType))
		i--
		dAtA[i] = 0x60
	}
	if m.GasLimit != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.GasLimit))
		i--
		dAtA[i] = 0x58
	}
	if m.InBlockHeight != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.InBlockHeight))
		i--
		dAtA[i] = 0x50
	}
	if len(m.InTxHash) > 0 {
		i -= len(m.InTxHash)
		copy(dAtA[i:], m.InTxHash)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.InTxHash)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x42
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.ReceiverChain != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.ReceiverChain))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x22
	}
	if m.SenderChainId != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.SenderChainId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgGasPriceVoter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgGasPriceVoter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgGasPriceVoter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Supply) > 0 {
		i -= len(m.Supply)
		copy(dAtA[i:], m.Supply)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.Supply)))
		i--
		dAtA[i] = 0x2a
	}
	if m.BlockNumber != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.BlockNumber))
		i--
		dAtA[i] = 0x20
	}
	if m.Price != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x18
	}
	if m.ChainId != 0 {
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(m.ChainId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintLegacyMsgs(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLegacyMsgs(dAtA []byte, offset int, v uint64) int {
	offset -= sovLegacyMsgs(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgAddToOutTxTracker) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	if m.ChainId != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.ChainId))
	}
	if m.Nonce != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.Nonce))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	if m.Proof != nil {
		l = m.Proof.Size()
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	l = len(m.BlockHash)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	if m.TxIndex != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.TxIndex))
	}
	return n
}

func (m *MsgAddToInTxTracker) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	if m.ChainId != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.ChainId))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	if m.CoinType != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.CoinType))
	}
	if m.Proof != nil {
		l = m.Proof.Size()
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	l = len(m.BlockHash)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	if m.TxIndex != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.TxIndex))
	}
	return n
}

func (m *MsgRemoveFromOutTxTracker) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	if m.ChainId != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.ChainId))
	}
	if m.Nonce != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.Nonce))
	}
	return n
}

func (m *MsgVoteOnObservedOutboundTx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	l = len(m.CctxHash)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	l = len(m.ObservedOutTxHash)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	if m.ObservedOutTxBlockHeight != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.ObservedOutTxBlockHeight))
	}
	l = m.ValueReceived.Size()
	n += 1 + l + sovLegacyMsgs(uint64(l))
	if m.Status != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.Status))
	}
	if m.OutTxChain != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.OutTxChain))
	}
	if m.OutTxTssNonce != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.OutTxTssNonce))
	}
	if m.CoinType != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.CoinType))
	}
	if m.ObservedOutTxGasUsed != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.ObservedOutTxGasUsed))
	}
	l = m.ObservedOutTxEffectiveGasPrice.Size()
	n += 1 + l + sovLegacyMsgs(uint64(l))
	if m.ObservedOutTxEffectiveGasLimit != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.ObservedOutTxEffectiveGasLimit))
	}
	return n
}

func (m *MsgVoteOnObservedInboundTx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	if m.SenderChainId != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.SenderChainId))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	if m.ReceiverChain != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.ReceiverChain))
	}
	l = m.Amount.Size()
	n += 1 + l + sovLegacyMsgs(uint64(l))
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	l = len(m.InTxHash)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	if m.InBlockHeight != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.InBlockHeight))
	}
	if m.GasLimit != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.GasLimit))
	}
	if m.CoinType != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.CoinType))
	}
	l = len(m.TxOrigin)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	l = len(m.Asset)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	if m.EventIndex != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.EventIndex))
	}
	return n
}

func (m *MsgGasPriceVoter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	if m.ChainId != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.ChainId))
	}
	if m.Price != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.Price))
	}
	if m.BlockNumber != 0 {
		n += 1 + sovLegacyMsgs(uint64(m.BlockNumber))
	}
	l = len(m.Supply)
	if l > 0 {
		n += 1 + l + sovLegacyMsgs(uint64(l))
	}
	return n
}

func sovLegacyMsgs(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLegacyMsgs(x uint64) (n int) {
	return sovLegacyMsgs(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgAddToOutTxTracker) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLegacyMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddToOutTxTracker: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddToOutTxTracker: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Proof == nil {
				m.Proof = &proofs.Proof{}
			}
			if err := m.Proof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxIndex", wireType)
			}
			m.TxIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxIndex |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLegacyMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddToInTxTracker) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLegacyMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddToInTxTracker: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddToInTxTracker: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinType", wireType)
			}
			m.CoinType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinType |= coin.CoinType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Proof == nil {
				m.Proof = &proofs.Proof{}
			}
			if err := m.Proof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxIndex", wireType)
			}
			m.TxIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxIndex |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLegacyMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveFromOutTxTracker) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLegacyMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveFromOutTxTracker: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveFromOutTxTracker: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLegacyMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVoteOnObservedOutboundTx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLegacyMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteOnObservedOutboundTx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteOnObservedOutboundTx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CctxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CctxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedOutTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObservedOutTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedOutTxBlockHeight", wireType)
			}
			m.ObservedOutTxBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObservedOutTxBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValueReceived", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValueReceived.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= chains.ReceiveStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutTxChain", wireType)
			}
			m.OutTxChain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutTxChain |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutTxTssNonce", wireType)
			}
			m.OutTxTssNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutTxTssNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinType", wireType)
			}
			m.CoinType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinType |= coin.CoinType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedOutTxGasUsed", wireType)
			}
			m.ObservedOutTxGasUsed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObservedOutTxGasUsed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedOutTxEffectiveGasPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObservedOutTxEffectiveGasPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedOutTxEffectiveGasLimit", wireType)
			}
			m.ObservedOutTxEffectiveGasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObservedOutTxEffectiveGasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLegacyMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVoteOnObservedInboundTx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLegacyMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVoteOnObservedInboundTx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVoteOnObservedInboundTx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderChainId", wireType)
			}
			m.SenderChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SenderChainId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverChain", wireType)
			}
			m.ReceiverChain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReceiverChain |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InBlockHeight", wireType)
			}
			m.InBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasLimit", wireType)
			}
			m.GasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinType", wireType)
			}
			m.CoinType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinType |= coin.CoinType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxOrigin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxOrigin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Asset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventIndex", wireType)
			}
			m.EventIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EventIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLegacyMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgGasPriceVoter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLegacyMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgGasPriceVoter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgGasPriceVoter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockNumber", wireType)
			}
			m.BlockNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Supply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Supply = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLegacyMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLegacyMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLegacyMsgs(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLegacyMsgs
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLegacyMsgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLegacyMsgs
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLegacyMsgs
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLegacyMsgs
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLegacyMsgs        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLegacyMsgs          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLegacyMsgs = fmt.Errorf("proto: unexpected end of group")
)
